name: Build prompts

on:
  push:
    branches: ["main"]
    paths:
      - "data/**"
      - "scripts/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install pyyaml
      - run: python scripts/build_prompts.py
      - run: |
          git config user.name "prompt-bot"
          git config user.email "prompt-bot@users.noreply.github.com"
          git add main_base/purpose/*.md PROMPTS.md
          git commit -m "chore: rebuild prompt pages" || exit 0
          git push
